version: 2

before:
  hooks:
    - go mod tidy -compat=1.24

builds:
  -
    goos:
      - darwin
      - linux
      - freebsd
      - windows

    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x

    flags:
      - -trimpath
      - --tags=kqueue

    ldflags:
      - -s -w -X main.version={{.Tag}}

    env:
      - CGO_ENABLED=0

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

changelog:
  sort: asc

nfpms:
  -
    maintainer: "MinIO Developers <dev@min.io>"
    homepage: https://github.com/minio/certgen
    formats:
      - deb
      - rpm
